name: encryption_interceptor
description: "A Dio interceptor that encrypts requests and decrypts responses using AES encryption, ensuring secure data transmission."
version: 1.0.0
homepage: "https://github.com/JaysonKhan/encryption_interceptor.git"
repository: "https://github.com/JaysonKhan/encryption_interceptor"
license: 'MIT'

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  rsa_encrypt: ^2.0.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

